# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: marketplace.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'marketplace.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11marketplace.proto\x12\x0bmarketplace\"\x87\x01\n\x11\x43reateItemRequest\x12\x10\n\x08owner_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\x0c\n\x04size\x18\x05 \x01(\t\x12\r\n\x05\x62rand\x18\x06 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x07 \x01(\t\"\x12\n\x10ListItemsRequest\"!\n\x0eGetItemRequest\x12\x0f\n\x07item_id\x18\x01 \x01(\x05\"\x9e\x01\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08owner_id\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x01\x12\x0c\n\x04size\x18\x06 \x01(\t\x12\r\n\x05\x62rand\x18\x07 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x08 \x01(\t\x12\x0e\n\x06status\x18\t \x01(\t\"=\n\x11ListItemsResponse\x12(\n\x05items\x18\x01 \x03(\x0b\x32\x19.marketplace.ItemResponse2\xe5\x01\n\x0bItemService\x12G\n\nCreateItem\x12\x1e.marketplace.CreateItemRequest\x1a\x19.marketplace.ItemResponse\x12J\n\tListItems\x12\x1d.marketplace.ListItemsRequest\x1a\x1e.marketplace.ListItemsResponse\x12\x41\n\x07GetItem\x12\x1b.marketplace.GetItemRequest\x1a\x19.marketplace.ItemResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'marketplace_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEITEMREQUEST']._serialized_start=35
  _globals['_CREATEITEMREQUEST']._serialized_end=170
  _globals['_LISTITEMSREQUEST']._serialized_start=172
  _globals['_LISTITEMSREQUEST']._serialized_end=190
  _globals['_GETITEMREQUEST']._serialized_start=192
  _globals['_GETITEMREQUEST']._serialized_end=225
  _globals['_ITEMRESPONSE']._serialized_start=228
  _globals['_ITEMRESPONSE']._serialized_end=386
  _globals['_LISTITEMSRESPONSE']._serialized_start=388
  _globals['_LISTITEMSRESPONSE']._serialized_end=449
  _globals['_ITEMSERVICE']._serialized_start=452
  _globals['_ITEMSERVICE']._serialized_end=681
# @@protoc_insertion_point(module_scope)
