syntax = "proto3";

package marketplace;

// Сервис товаров
service ItemService {
  rpc CreateItem (CreateItemRequest) returns (ItemResponse);
  rpc ListItems (ListItemsRequest) returns (ListItemsResponse);
  rpc GetItem (GetItemRequest) returns (ItemResponse);
}

// --- Запросы ---
message CreateItemRequest {
  int32 owner_id = 1;
  string title = 2;
  string description = 3;
  double price = 4;
  string size = 5;
  string brand = 6;
  string category = 7;
}

message ListItemsRequest {}

message GetItemRequest {
  int32 item_id = 1;
}

// --- Ответы ---
message ItemResponse {
  int32 id = 1;
  int32 owner_id = 2;
  string title = 3;
  string description = 4;
  double price = 5;
  string size = 6;
  string brand = 7;
  string category = 8;
  string status = 9;
}

message ListItemsResponse {
  repeated ItemResponse items = 1;
}